### ISSUE TITLE
Orleans 1.5, Streams and Rebinding Grain Reference

### ISSUE THREAD

**Issue by Xanatus** [OrleansContrib/Orleans.Providers.MongoDB#21]
I'm trying to get Orleans Streams to work with MongoDB.

Orleans 1.5+ requires rebinding of deserialized grain references via IGrainFactory.BindGrainReference().

Because of this, I get following exception on stream.OnNextAsync():

> Orleans.Runtime.GrainReferenceNotBoundException: Attempted to use a GrainReference which has not been bound to the runtime

Is there any way that Orleans.Providers.MongoDB could rebind references itself?
If not, do you have any suggestions on how I can rebind references and get streams with mongo to work?

**Comment by laredoza** [comment]
Hi,

This is the first time that I've heard about Orleans streams but it seems interesting. Can I ask that you fork the main project and add a few classes so that we can recreate this issue?

Memo to self:

Documentation:
https://dotnet.github.io/orleans/Documentation/Orleans-Streams/Streams-Extensibility.html

Azure Example:
https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapterFactory.cs

**Comment by Xanatus** [comment]
I was able to fix my issue.

I fixed the issue by implementing the GrainReferenceConverter from the orleans json serializer: https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/OrleansJsonSerializer.cs

This is only needed for orleans 1.5+. On older orleans rebinding wasn't necessary.

**Comment by laredoza** [comment]
Great to hear. Are you busy writing your own Provider? If so, would you consider creating a pull request? It would be nice to add the functionality.

**Comment by Xanatus** [comment]
I don't really use github so I have no idea about pull requests etc.

But I can explain exactly how to fix your code for 1.5:

All you need to do is copy past the GrainReferenceConverter class from offical orleans serializer.
https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/OrleansJsonSerializer.cs

I don't think you need the other converters, so you can remove them from the internalSerializer settings.

Then in BaseJSONStorageProvider.cs in the Init() method, you add the converter:

`serializerSettings.Converters.Add(new GrainReferenceConverter(providerRuntime.GrainFactory));`

That's all. Now grain reference serialization/deserialization should work as expected and therefore streams as well :)

**Comment by laredoza** [comment]
I've uploaded a preview version package:

https://www.nuget.org/packages/Orleans.Providers.MongoDB/0.1.3-preview

I'd appreciate it if you can test it. Thanks

**Comment by Xanatus** [comment]
What .Net framework version do I need for your preview? I'm gettin this error:

> Could not install package 'Orleans.Providers.MongoDB 0.1.3-preview'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by laredoza** [comment]
Dotnet 4.6.1 hould be okay. As far as I know this could be due to the fact that the library has been upgraded to DotnetStandard 1.6 to enable dotnet core support. 

I found the following: https://github.com/dotnet/standard/issues/410:

For anyone that might still be hitting this you can workaround it by explicitly making the .NET Framework project a ProjectReference based project by setting the following property in the project:

<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
There is also a good change you will need auto-bindingredirects as well so make sure that is set in your project:

<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>

I'm going to have a look at this a bit later and try and confirm that this is the issue

**Comment by laredoza** [comment]
Okay my apologies, I thought I understood how dotnetstandard works, but clearly not. I've added a new target for 4.6.1. It should work now:

https://www.nuget.org/packages/Orleans.Providers.MongoDB/0.1.5-preview

**Comment by Xanatus** [comment]
Seems to work fine. Both instal and streams working :+1:

**Comment by laredoza** [comment]
Okay great. I'm going to close this issue then. If you hit any other issues let me know.

I've published a new version on Nuget:
https://www.nuget.org/packages/Orleans.Providers.MongoDB/0.1.5
