### ISSUE TITLE
RC2 Code Review

### ISSUE THREAD

**Issue by ReubenBond** [OrleansContrib/Orleans.Providers.MongoDB#39]
* [ ] Options should be injected as `IOptions<TOptions>` rather than `TOptions`
https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/ba696c70d889b145b1a2558ce3704550f65e18a4/Orleans.Providers.MongoDB/Configuration/MongoDBGrainStorageOptionsValidator.cs#L10

* [ ] Since MongoDB now supports multi-document transactions, I recommend implementing the extended membership protocol. Total ordering for cluster membership table versions is beneficial, see: http://dotnet.github.io/orleans/Documentation/Runtime-Implementation-Details/Cluster-Management.html#extension-to-totally-order-membership-views 
https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/ba696c70d889b145b1a2558ce3704550f65e18a4/Orleans.Providers.MongoDB/Membership/Store/MongoMembershipCollection.cs#L15

* [ ] Could the LINQ queries (`Status == Active`, `ProxyPort > 0`) be added to the initial query to reduce the number of results from an unbounded number? Low priority.
https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/ba696c70d889b145b1a2558ce3704550f65e18a4/Orleans.Providers.MongoDB/Membership/Store/MongoMembershipCollection.cs#L67

* [ ] Should there be an ETag check here?
https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/ba696c70d889b145b1a2558ce3704550f65e18a4/Orleans.Providers.MongoDB/Reminders/Store/MongoReminderCollection.cs#L154

* [ ] If possible, I would entirely remove the option for binary serialization using SerializationManager, since it doesn't have any in-built facilities for version-tolerance.
https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/ba696c70d889b145b1a2558ce3704550f65e18a4/Orleans.Providers.MongoDB/StorageProviders/Serializers/BinaryGrainStateSerializer.cs#L6

**Comment by ReubenBond** [comment]
> Also, the etag is checked as a constraint whenever we have a write that is not an intentional overwrite.

Do you mean that the MongoDB provider is already checking the ETag in the reminder update? I couldn't spot it.

**Comment by galvesribeiro** [comment]
Not Mongo, the CosmosDB provider I created on Orleans contrib.

Check this: https://github.com/OrleansContrib/Orleans.CosmosDB/blob/master/src/Orleans.Persistence.CosmosDB/Sprocs/WriteState.js#L24

**Comment by galvesribeiro** [comment]
Reminders follow the same pattern: https://github.com/OrleansContrib/Orleans.CosmosDB/blob/master/src/Orleans.Reminders.CosmosDB/Sprocs/UpsertRow.js#L10

**Comment by SebastianStehle** [comment]
MongodB 4.0 is not even released yet and it will take some time for everybody to upgrade it.

**Comment by laredoza** [comment]
2. I have a few concerns with regards to implementing transactions at this stage. Mainly due to not having worked with it at all.

- If we use transactions what will happen if transactions are turned off on the MongoDb 4 database?What happens when we use a pre v4 database. Does the driver handle this?
- What is the performance hit one will takes by enabling transactions? I think most applications written for Mongo wouldn't require this. Maybe this feature would give it a more compelling reason to replace a  relational database. Would be interesting to see what this change brings.
- My past experience with Mongo 3.0 wasn't great (Wiredshark had several bugs / performance isssues). It took a while for this to be sorted out  So I'm not sure if I'd climb in at v4 immediately.
 
Should we not wait for version 4 to come out before supporting this?
 
5. The binary serialization was added because of the following: 
https://github.com/OrleansContrib/Orleans.Providers.MongoDB/pull/23

Would there be a work around for this issue without using binary serialization?

**Comment by ReubenBond** [comment]
@laredoza transactions ought to be fairly cheap and this particular collection we're talking about (cluster membership) is updated relatively infrequently. As for the other points, I can't speak to them since I haven't touched MongoDB since 2.0 days

**Comment by SebastianStehle** [comment]
I totally agree with @laredoza

**Comment by ReubenBond** [comment]
The enhanced membership protocol could also be implemented without multi-doc transactions if all operations were performed on a single doc. That might limit the size of the table, but the limit shouldn't be too restrictive (at least 16MB) as long as long-dead silos are eventually removed

**Comment by SebastianStehle** [comment]
I would prefer this. 16 MB should be big enough for even clusters of thousands of machines.
